#pragma once

#define KC_MOUSE_BUTTON_1		0
#define KC_MOUSE_BUTTON_2		1
#define KC_MOUSE_BUTTON_3		2
#define KC_MOUSE_BUTTON_4		3
#define KC_MOUSE_BUTTON_5		4
#define KC_MOUSE_BUTTON_6		5
#define KC_MOUSE_BUTTON_7		6
#define KC_MOUSE_BUTTON_8		7
#define KC_MOUSE_BUTTON_LAST	KC_MOUSE_BUTTON_8
#define KC_MOUSE_BUTTON_LEFT	KC_MOUSE_BUTTON_1
#define KC_MOUSE_BUTTON_RIGHT	KC_MOUSE_BUTTON_2
#define KC_MOUSE_BUTTON_MIDDLE	KC_MOUSE_BUTTON_3